#!/usr/bin/env python3
"""Test whether low teacher EOS mass on student rollouts is a scoring artifact.

The OPD teacher assigns almost no termination probability at the positions where
the Gemma student stops. Either the scoring path mis-conditions the teacher, or
the student's trajectories are genuinely off-distribution for it.

This separates the two by holding the prompt and the scoring code fixed and
varying only who wrote the completion:

  teacher_own   completions generated BY the teacher itself
  student_own   completions generated by the base student

Both are scored through the same forward pass, and the teacher's probability of
its terminal tokens is read at the position that predicts the final token. If
teacher_own scores near 1.0 the scoring path is sound, and a near-zero
student_own score is a real distribution-shift result rather than a bug.

A control also scores each teacher_own completion at a random interior position,
where terminal probability should be low. If that control is not low the metric
itself is not discriminating.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
import torch


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--student-model", required=True)
    p.add_argument("--teacher-model", required=True)
    p.add_argument("--input-parquet", type=Path, required=True)
    p.add_argument("--output-dir", type=Path, required=True)
    p.add_argument("--num-prompts", type=int, default=64)
    p.add_argument("--n", type=int, default=2)
    p.add_argument("--max-tokens", type=int, default=4096)
    p.add_argument("--max-model-len", type=int, default=8192)
    p.add_argument("--temperature", type=float, default=1.0)
    p.add_argument("--top-p", type=float, default=1.0)
    p.add_argument("--gpu-memory-utilization", type=float, default=0.45)
    p.add_argument("--seed", type=int, default=0)
    return p.parse_args()


def build_prompt_ids(student_model, teacher_model, messages_list):
    """Reproduce exactly what verl's RLHFDataset builds during training."""
    from transformers import AutoTokenizer

    from verl.utils.tokenizer import load_chat_template_text, resolve_chat_template_kwargs

    tok = AutoTokenizer.from_pretrained(student_model, trust_remote_code=True)
    template, _ = load_chat_template_text(teacher_model, trust_remote_code=True)
    kwargs = resolve_chat_template_kwargs(
        tokenizer=tok,
        chat_template=template,
        enable_thinking=False,
        base_kwargs={"tokenize": False, "add_generation_prompt": True},
    )
    prompts = [tok.apply_chat_template(list(m), **kwargs) for m in messages_list]
    return tok, [tok(p, add_special_tokens=False)["input_ids"] for p in prompts]


def terminal_token_ids(model_path) -> list[int]:
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from run_semantics import discover_model_eos_token_ids

    return discover_model_eos_token_ids(model_path)


def generate(model_path, prompt_ids, stop_ids, args, label):
    from vllm import LLM, SamplingParams, TokensPrompt

    llm = LLM(
        model=model_path,
        trust_remote_code=True,
        max_model_len=args.max_model_len,
        gpu_memory_utilization=args.gpu_memory_utilization,
        tensor_parallel_size=1,
        seed=args.seed,
    )
    params = SamplingParams(
        n=args.n,
        temperature=args.temperature,
        top_p=args.top_p,
        max_tokens=args.max_tokens,
        stop_token_ids=stop_ids,
    )
    outputs = llm.generate([TokensPrompt(prompt_token_ids=ids) for ids in prompt_ids], params)
    rows = []
    for prompt_index, out in enumerate(outputs):
        for completion in out.outputs:
            ids = list(completion.token_ids)
            terminated = bool(ids) and ids[-1] in stop_ids
            rows.append(
                {
                    "prompt_index": prompt_index,
                    "completion_ids": ids,
                    "terminated": terminated,
                    "finish_reason": completion.finish_reason,
                }
            )
    n_term = sum(r["terminated"] for r in rows)
    print(f"[{label}] {len(rows)} completions, {n_term} terminated ({n_term/max(len(rows),1):.1%})", flush=True)
    del llm
    import gc

    import torch.distributed as dist

    gc.collect()
    torch.cuda.empty_cache()
    if dist.is_initialized():
        dist.destroy_process_group()
    return rows


def score(teacher_model, prompt_ids, rows, eos_ids, label, rng):
    """Teacher probability of the terminal class at the position predicting the last token."""
    import transformers
    from transformers import AutoConfig, AutoModelForCausalLM

    # Resolve the exact architecture class by name. The Auto* mappings do not cover
    # every multimodal config (Gemma3Config is not in AutoModelForVision2Seq), and
    # naming the class avoids depending on those mappings entirely.
    config = AutoConfig.from_pretrained(teacher_model, trust_remote_code=True)
    architecture = config.architectures[0]
    cls = getattr(transformers, architecture, None) or AutoModelForCausalLM
    print(f"[{label}] scoring with {cls.__name__} for architecture {architecture}", flush=True)
    model = cls.from_pretrained(teacher_model, torch_dtype=torch.bfloat16, trust_remote_code=True).cuda().eval()

    at_end, at_interior = [], []
    with torch.no_grad():
        for row in rows:
            if not row["terminated"]:
                continue
            row["terminal_mass_index"] = len(at_end)
            ids = prompt_ids[row["prompt_index"]] + row["completion_ids"]
            x = torch.tensor([ids], device="cuda")
            logits = model(input_ids=x).logits[0].float()
            log_probs = torch.log_softmax(logits, dim=-1)
            # Position len(ids)-2 predicts the final (terminal) token.
            end_pos = len(ids) - 2
            at_end.append(torch.logsumexp(log_probs[end_pos, eos_ids], dim=-1).exp().item())
            lo = len(prompt_ids[row["prompt_index"]])
            if end_pos > lo + 1:
                pos = rng.integers(lo, end_pos)
                at_interior.append(torch.logsumexp(log_probs[pos, eos_ids], dim=-1).exp().item())
    del model
    torch.cuda.empty_cache()
    print(f"[{label}] scored {len(at_end)} terminated completions", flush=True)
    return np.array(at_end), np.array(at_interior)


def describe(name, values):
    if values.size == 0:
        return {"group": name, "n": 0}
    return {
        "group": name,
        "n": int(values.size),
        "median": float(np.median(values)),
        "mean": float(values.mean()),
        "frac_above_0.5": float(np.mean(values > 0.5)),
        "frac_above_0.1": float(np.mean(values > 0.1)),
        "frac_below_1e-3": float(np.mean(values < 1e-3)),
    }


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    frame = pd.read_parquet(args.input_parquet).head(args.num_prompts)
    tok, prompt_ids = build_prompt_ids(args.student_model, args.teacher_model, frame["prompt"].tolist())

    teacher_eos = terminal_token_ids(args.teacher_model)
    student_eos = terminal_token_ids(args.student_model)
    print(f"teacher terminal ids={teacher_eos}  student terminal ids={student_eos}", flush=True)
    scored_ids = sorted(set(teacher_eos) | set(student_eos))

    teacher_rows = generate(args.teacher_model, prompt_ids, teacher_eos, args, "teacher_own")
    student_rows = generate(args.student_model, prompt_ids, student_eos, args, "student_own")

    t_end, t_interior = score(args.teacher_model, prompt_ids, teacher_rows, scored_ids, "teacher_own", rng)
    s_end, _ = score(args.teacher_model, prompt_ids, student_rows, scored_ids, "student_own", rng)

    # Split the student's terminations by whether the answer was actually correct.
    # If a bad answer is the reason the teacher will not end the turn, correct
    # completions should score much higher than incorrect ones.
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "val" / "eval"))
    from utils import grade_answer_verl

    truths = [r["ground_truth"] for r in frame["reward_model"]]
    correct_mask, texts = [], []
    for row in student_rows:
        if not row["terminated"]:
            continue
        body = tok.decode(row["completion_ids"], skip_special_tokens=True)
        texts.append(body)
        try:
            ok = bool(grade_answer_verl(body, truths[row["prompt_index"]]))
        except Exception:
            ok = False
        correct_mask.append(ok)
    correct_mask = np.array(correct_mask, dtype=bool)

    # Does the completion actually END with a boxed answer? A loose search for
    # "boxed" or "final answer" gives false positives, because base students
    # restate the prompt's own instruction to box the answer, so require the
    # boxed value to be the last thing in the completion.
    ends_boxed = re.compile(r"\\boxed\{[^{}]{1,40}\}[\s$)\]\\]*$")
    finished = np.array([bool(ends_boxed.search(t.strip())) for t in texts], dtype=bool)
    well_formed = {
        "rate": float(finished.mean()) if finished.size else 0.0,
        "n_finished": int(finished.sum()),
        "n_total": int(finished.size),
        "finished": describe("student_ends_with_boxed_answer", s_end[finished]),
        "unfinished": describe("student_does_not_end_with_boxed_answer", s_end[~finished]),
    }
    by_correctness = {
        "student_correct": describe("student_own_correct", s_end[correct_mask]),
        "student_incorrect": describe("student_own_incorrect", s_end[~correct_mask]),
        "student_accuracy": float(correct_mask.mean()) if correct_mask.size else 0.0,
    }
    (args.output_dir / "student_completions.json").write_text(
        json.dumps(
            [{"text": t, "correct": bool(c), "terminal_mass": float(m)}
             for t, c, m in zip(texts, correct_mask, s_end)],
            indent=2,
        )
    )

    summary = {
        "student_model": args.student_model,
        "teacher_model": args.teacher_model,
        "scored_terminal_ids": scored_ids,
        "num_prompts": args.num_prompts,
        "n": args.n,
        "groups": [
            describe("teacher_own_at_its_own_stop", t_end),
            describe("teacher_own_at_random_interior_position", t_interior),
            describe("student_own_at_its_own_stop", s_end),
        ],
        "student_split_by_correctness": by_correctness,
        "student_split_by_well_formed_ending": well_formed,
    }
    (args.output_dir / "summary.json").write_text(json.dumps(summary, indent=2))
    np.savez_compressed(
        args.output_dir / "terminal_probs.npz",
        teacher_own_end=t_end,
        teacher_own_interior=t_interior,
        student_own_end=s_end,
        scored_terminal_ids=np.array(scored_ids),
    )
    print(json.dumps(summary, indent=2), flush=True)


if __name__ == "__main__":
    main()
